---
- name: ssh_key_add
  authorized_key: user={{ remote_user }}  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
 
- name: Install_basic_tools
  apt: pkg={{item}} state=installed force=yes
  sudo: yes
  tags:
  - install_basic
  with_items:
    - "{{ common_packages }}"
