
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "dev-station"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :private_network, ip: "192.168.56.100"
  # instead of 172.28.128.5 use your whatever ip you want just
  # do not forget to change it in the Virtualbox preferences as well
  # on the host run: sudo route -n add 10.0.0.205/24 192.168.56.100
  # instead of 10.0.3.0 use your eth0 ip
  config.vm.provider "virtualbox" do |v|
    v.memory = 6144
    v.cpus = 2
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
  config.vm.synced_folder './vagrant_share', '/vagrant', type: 'nfs_guest', mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1']
end
