---
- name: common | install packages
  yum: pkg={{ item }} state=latest update_cache=yes
  with_items:
     - git
     - htop
     - vim
     - bash-completion
  tags:
     - yum

- name: common | copy initial .bashrc file
  template: src=.bashrc dest=~
  tags:
     - configuration

- name: common | configure git
  copy: src=.gitconfig dest=~/.gitconfig
  tags:
     - configuration
