---
- name: yum | install packages
  yum: pkg={{ item }} state=latest update_cache=yes
  with_items:
     - git
     - htop
     - vim
     - nano
  tags:
     - yum
#==================================
#==  GENERAL CONFIGURATION ========
#==================================

- name: configuration | get git-completion.bash
  get_url: url=https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash dest=~/.git-completion.bash mode=0755

- name: configuration | copy initial .bashrc file
  template: src=.bashrc dest=~
  tags:
     - configuration

- name: configuration | Apply .bashrc
  shell: . ~/.bashrc
  tags:
     - configuration

#============================
#============ GIT ===========
#============================

- name: git | remove the 'credentials' section from local repo
  shell: cd ~/DonkeyBites && git config --local --remove-section credential
  ignore_errors: yes
  tags:
     - git

- name: git | configure cache for passwords
  shell: cd ~/DonkeyBites && git config --local credential.helper "cache --timeout=604800"
  tags:
     - git


- name: git | remove the user section from local repo
  shell: cd ~/DonkeyBites && git config --local --remove-section user
  tags:
     - git

- name: git | clone git DonkeyBites if not exists
  git:
     repo=https://github.com/doronshai/DonkeyBites.git
     dest=~/DonkeyBites
     update=no
  tags:
     - git

- name: git | configure git user
  shell: cd ~/DonkeyBites && git config --local user.name "Doron Shai"
  tags:
     - git

- name: git | configure git email
  shell: cd ~/DonkeyBites && git config --local user.email "doronshai@gmail.com"
  tags:
     - git
