---
- name: yum | install packages
  yum: name={{ item }} state=latest update_cache=yes
  sudo: yes
  with_items:
     - git
     - htop
     - vim
     - nano
     - bash-completion
  when: (ansible_distribution == "CentOS")
  tags:
     - install

- name: apt-get | install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  sudo: yes
  with_items:
     - git
     - htop
     - vim
     - nano
     - git-completion
  when: (ansible_distribution == "Ubuntu")
  tags:
    - install


#======================================
#======  GENERAL CONFIGURATION ========
#======================================

- name: configuration | copy initial .bashrc file
  template: src=.bashrc dest=~
  tags:
     - configuration

- name: configuration | Apply .bashrc
  shell: . ~/.bashrc
  tags:
     - configuration

#==============================
#============ GIT =============
#==============================

- name: git | clone git DonkeyBites if not exists
  git:
     repo=https://github.com/doronshai/DonkeyBites.git
     dest=~/DonkeyBites
     update=no
  tags:
     - git

- name: git | remove the 'credentials' section from local repo
  shell: cd ~/DonkeyBites && git config --local --remove-section credential
  ignore_errors: yes
  tags:
     - git

- name: git | configure cache for passwords
  shell: cd ~/DonkeyBites && git config --local credential.helper "cache --timeout=604800"
  tags:
     - git


- name: git | remove the user section from local repo
  shell: cd ~/DonkeyBites && git config --local --remove-section user
  ignore_errors: yes
  tags:
     - git

- name: git | configure git user
  shell: cd ~/DonkeyBites && git config --local user.name "Doron Shai"
  tags:
     - git

- name: git | configure git email
  shell: cd ~/DonkeyBites && git config --local user.email "doronshai@gmail.com"
  tags:
     - git
