#!/usr/local/bin/python2.7
#

import sys
import logging
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), "../utils"))
hook = os.path.basename(sys.argv[0])

import utils
import git_utils
import jira_utils
import jenkins_utils



def main():
    utils.init_logger()
    try:
        version = git_utils.git_config_get(git_utils.SANDBOX_VERSION)
        logging.debug("**** post-receive hook running version: %s ****" %version )
        lines = sys.stdin.readlines()
        # Get commit info
        old_rev, new_rev, ref_name = git_utils.parse_receive_line(lines[0])
        user = git_utils.get_push_user()
        for line in lines:
            logging.debug("git line: %s" %line )
        utils.run(lines,version,old_rev, new_rev, user,ref_name,'true')
        logging.debug("**** post-receive hook finished running ****" )
    except:
        logging.warning( "Fail triggering job, Unexpected error", exc_info=True )
    

if __name__ == '__main__':
    main()
